stages:
  - validate

validate_test_environment:
  image: ciscotestautomation/pyats:latest
  stage: validate
  script:
    - source /pyats/bin/activate
    -  ./run.sh

  artifacts:
      name: "{{ cookiecutter.project_name}}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
      when: always
      paths:
        - ./TaskLog.html
